# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dom Barnes
email: dom@dombarnes.com
meta_description: The personal website of Dom Barnes
description: > # this means to ignore newlines until "baseurl:"
  Hi. I'm <a href="//twitter.com/domster">@domster</a>. I livei in Birmingham and work at Trilby. I occasionally play bass, pretend to code and take photographs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://archive.dombarnes.com" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title
# paginate: 10
# paginate_path: /page:num
timezone:    Europe/London

owner:
  name:           Dom Barnes
  # avatar:         railstutor.png
  email:          dom@dombarnes.com
  conversion:     http://archive.dombarnes.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:       domster
  github:        dombarnes
  stackexchange:
  linkedin:      dombarnes
  instagram:     dombarnes
  flickr:        domster83
  tumblr:        dombarnes

# Header links
links:
  - title: Full List
    url: /posts/  
footer_links:
  - title: Main Site
    url: http://dombarnes.com

# Build settings
markdown: kramdown
gems:
  - kramdown
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - config.ru
  - Gemfile
  - Gemfile.lock
  - vendor
  - Procfile
  - Rakefile

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      author: "Dom Barnes"
      layout: "default"
